In [1]:
!nvidia-smi

Thu Oct  8 10:27:42 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   54C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [2]:
import torch

print("GPU available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

GPU available: True
GPU: Tesla T4

In [3]:
!git clone https://github.com/amandogra2802/Text-Summarizer-Project.git

Cloning into 'Text-Summarizer-Project'...
remote: Enumerating objects: 34, done.
remote: Counting objects: 100% (34/34), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 34 (delta 6), reused 28 (delta 4), pack-reused 0 (from 0)
Receiving objects: 100% (34/34), 6.87 KiB | 6.87 MiB/s, done.
Resolving deltas: 100% (6/6), done.

In [4]:
%cd Text-Summarizer-Project

/content/Text-Summarizer-Project

In [5]:
!ls

app.py	Dockerfile  main.py	 README.md	   research  src
config	LICENSE     params.yaml  requirements.txt  setup.py  template.py

In [6]:
!pip install transformers[sentencepiece] datasets sacrebleu rouge_score py7zr -q

  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.8/100.8 kB 9.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.2/72.2 kB 8.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 492.7/492.7 kB 29.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.8/100.8 kB 11.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.4/52.4 kB 5.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 144.5/144.5 kB 16.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.6/129.6 kB 14.8 MB/s eta 0:00:00
  Building wheel for rouge_score (setup.py) ... done

In [7]:
!pip install --upgrade accelerate
!pip uninstall -y transformers accelerate
!pip install transformers accelerate

Requirement already satisfied: accelerate in /usr/local/lib/python3.13/dist-packages (1.15.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.13/dist-packages (from accelerate) (2.1.3)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from accelerate) (26.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.13/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.13/dist-packages (from accelerate) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from accelerate) (2.11.0+cu130)
Requirement already satisfied: huggingface_hub>=0.21.0 in /usr/local/lib/python3.13/dist-packages (from accelerate) (1.33.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.13/dist-packages (from accelerate) (0.8.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub>=0.21.0->accelerate) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub>=0.21.0->accelerate) (4.0.7)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub>=0.21.0->accelerate) (2025.12.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub>=0.21.0->accelerate) (1.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub>=0.21.0->accelerate) (0.28.1)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub>=0.21.0->accelerate) (4.67.3)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub>=0.21.0->accelerate) (4.16.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->accelerate) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->accelerate) (3.7)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: cuda-toolkit==13.0.2 in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate) (13.0.2)
Requirement already satisfied: cuda-bindings<14,>=13.0.3 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->accelerate) (13.0.3)
Requirement already satisfied: nvidia-cudnn-cu13==9.19.0.56 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->accelerate) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu13==0.8.0 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->accelerate) (0.8.0)
Requirement already satisfied: nvidia-nccl-cu13==2.28.9 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->accelerate) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu13==3.4.5 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->accelerate) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->accelerate) (3.6.0)
Requirement already satisfied: nvidia-cublas==13.1.0.3.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate) (13.1.0.3)
Requirement already satisfied: nvidia-cuda-runtime==13.0.96.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate) (13.0.96)
Requirement already satisfied: nvidia-cufft==12.0.0.61.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate) (12.0.0.61)
Requirement already satisfied: nvidia-cufile==1.15.1.6.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate) (1.15.1.6)
Requirement already satisfied: nvidia-cuda-cupti==13.0.85.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate) (13.0.85)
Requirement already satisfied: nvidia-curand==10.4.0.35.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate) (10.4.0.35)
Requirement already satisfied: nvidia-cusolver==12.0.4.66.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate) (12.0.4.66)
Requirement already satisfied: nvidia-cusparse==12.6.3.3.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate) (12.6.3.3)
Requirement already satisfied: nvidia-nvjitlink==13.0.88.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate) (13.0.88)
Requirement already satisfied: nvidia-cuda-nvrtc==13.0.88.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate) (13.0.88)
Requirement already satisfied: nvidia-nvtx==13.0.85.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate) (13.0.85)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.13/dist-packages (from cuda-bindings<14,>=13.0.3->torch>=2.0.0->accelerate) (1.8.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (4.15.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (3.20)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Found existing installation: transformers 5.18.0
Uninstalling transformers-5.18.0:
  Successfully uninstalled transformers-5.18.0
Found existing installation: accelerate 1.15.0
Uninstalling accelerate-1.15.0:
  Successfully uninstalled accelerate-1.15.0
Collecting transformers
  Downloading transformers-5.19.0-py3-none-any.whl.metadata (32 kB)
Collecting accelerate
  Downloading accelerate-1.15.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: huggingface-hub<3.0,>=1.31.0 in /usr/local/lib/python3.13/dist-packages (from transformers) (1.33.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.13/dist-packages (from transformers) (2.1.3)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from transformers) (26.3)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.13/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.13/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<0.24.0,>=0.23.1 in /usr/local/lib/python3.13/dist-packages (from transformers) (0.23.2)
Requirement already satisfied: typer in /usr/local/lib/python3.13/dist-packages (from transformers) (0.27.2)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.13/dist-packages (from transformers) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in /usr/local/lib/python3.13/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.13/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from accelerate) (2.11.0+cu130)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (4.0.7)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (2025.12.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (1.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (4.16.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->accelerate) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->accelerate) (3.7)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: cuda-toolkit==13.0.2 in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate) (13.0.2)
Requirement already satisfied: cuda-bindings<14,>=13.0.3 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->accelerate) (13.0.3)
Requirement already satisfied: nvidia-cudnn-cu13==9.19.0.56 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->accelerate) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu13==0.8.0 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->accelerate) (0.8.0)
Requirement already satisfied: nvidia-nccl-cu13==2.28.9 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->accelerate) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu13==3.4.5 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->accelerate) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.13/dist-packages (from torch>=2.0.0->accelerate) (3.6.0)
Requirement already satisfied: nvidia-cublas==13.1.0.3.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate) (13.1.0.3)
Requirement already satisfied: nvidia-cuda-runtime==13.0.96.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate) (13.0.96)
Requirement already satisfied: nvidia-cufft==12.0.0.61.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate) (12.0.0.61)
Requirement already satisfied: nvidia-cufile==1.15.1.6.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate) (1.15.1.6)
Requirement already satisfied: nvidia-cuda-cupti==13.0.85.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate) (13.0.85)
Requirement already satisfied: nvidia-curand==10.4.0.35.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate) (10.4.0.35)
Requirement already satisfied: nvidia-cusolver==12.0.4.66.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate) (12.0.4.66)
Requirement already satisfied: nvidia-cusparse==12.6.3.3.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate) (12.6.3.3)
Requirement already satisfied: nvidia-nvjitlink==13.0.88.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate) (13.0.88)
Requirement already satisfied: nvidia-cuda-nvrtc==13.0.88.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate) (13.0.88)
Requirement already satisfied: nvidia-nvtx==13.0.85.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.0.0->accelerate) (13.0.85)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.13/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.13/dist-packages (from typer->transformers) (0.0.5)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.13/dist-packages (from cuda-bindings<14,>=13.0.3->torch>=2.0.0->accelerate) (1.8.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<3.0,>=1.31.0->transformers) (4.15.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<3.0,>=1.31.0->transformers) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<3.0,>=1.31.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<3.0,>=1.31.0->transformers) (3.20)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<3.0,>=1.31.0->transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer->transformers) (2.21.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)
Downloading transformers-5.19.0-py3-none-any.whl (12.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.6/12.6 MB 102.2 MB/s eta 0:00:00
Downloading accelerate-1.15.0-py3-none-any.whl (394 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 394.3/394.3 kB 35.8 MB/s eta 0:00:00
Installing collected packages: transformers, accelerate
Successfully installed accelerate-1.15.0 transformers-5.19.0

In [9]:
from transformers import pipeline, set_seed
from datasets import load_dataset, load_from_disk
import matplotlib.pyplot as plt
import pandas as pd
import evaluate

from transformers import AutoModelForSeq2SeqLM, AutoTokenizer

import nltk
from nltk.tokenize import sent_tokenize

from tqdm import tqdm
import torch

nltk.download("punkt")

ModuleNotFoundError: No module named 'evaluate'

In [10]:
!pip install -q evaluate

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 5.2 MB/s eta 0:00:00

In [11]:
from transformers import pipeline, set_seed
from datasets import load_dataset, load_from_disk
import matplotlib.pyplot as plt
import pandas as pd
import evaluate

from transformers import AutoModelForSeq2SeqLM, AutoTokenizer

import nltk
from nltk.tokenize import sent_tokenize

from tqdm import tqdm
import torch

nltk.download("punkt")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [12]:
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [13]:
model_ckpt = "google/pegasus-cnn_dailymail"

tokenizer = AutoTokenizer.from_pretrained(model_ckpt)

model_pegasus = AutoModelForSeq2SeqLM.from_pretrained(model_ckpt).to(device)

config.json:   0%|          | 0.00/1.12k [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer_config.json:   0%|          | 0.00/88.0 [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/1.91M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/65.0 [00:00<?, ?B/s]

pytorch_model.bin: reconstructing file:   0%|          |  0.00B / 2.28GB

pytorch_model.bin: downloading bytes:           |  0.00B

model.safetensors: reconstructing file:   0%|          |  0.00B / 2.28GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/680 [00:00<?, ?it/s]

[transformers] PegasusForConditionalGeneration LOAD REPORT from: google/pegasus-cnn_dailymail
Key                                  | Status  |
-------------------------------------+---------+-
model.encoder.embed_positions.weight | MISSING |
model.decoder.embed_positions.weight | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

generation_config.json:   0%|          | 0.00/280 [00:00<?, ?B/s]

In [14]:
# download & unzip data

!wget https://github.com/entbappy/Branching-tutorial/raw/master/summarizer-data.zip
!unzip summarizer-data.zip

--2026-10-08 10:57:32--  https://github.com/entbappy/Branching-tutorial/raw/master/summarizer-data.zip
Resolving github.com (github.com)... 140.82.113.3
Connecting to github.com (github.com)|140.82.113.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/entbappy/Branching-tutorial/master/summarizer-data.zip [following]
--2026-10-08 10:57:33--  https://raw.githubusercontent.com/entbappy/Branching-tutorial/master/summarizer-data.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7903594 (7.5M) [application/zip]
Saving to: ‘summarizer-data.zip’

summarizer-data.zip 100%[===================>]   7.54M  --.-KB/s    in 0.06s

2026-10-08 10:57:33 (121 MB/s) - ‘summarizer-data.zip’ saved [7903594/7903594]

Archive:  summarizer-data.zip
  inflating: samsum-test.csv
  inflating: samsum-train.csv
  inflating: samsum-validation.csv
   creating: samsum_dataset/
 extracting: samsum_dataset/dataset_dict.json
   creating: samsum_dataset/test/
  inflating: samsum_dataset/test/data-00000-of-00001.arrow
  inflating: samsum_dataset/test/dataset_info.json
  inflating: samsum_dataset/test/state.json
   creating: samsum_dataset/train/
  inflating: samsum_dataset/train/data-00000-of-00001.arrow
  inflating: samsum_dataset/train/dataset_info.json
  inflating: samsum_dataset/train/state.json
   creating: samsum_dataset/validation/
  inflating: samsum_dataset/validation/data-00000-of-00001.arrow
  inflating: samsum_dataset/validation/dataset_info.json
  inflating: samsum_dataset/validation/state.json

In [15]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [16]:
dataset_samsum = load_from_disk('samsum_dataset')
dataset_samsum

DatasetDict({
    train: Dataset({
        features: ['id', 'dialogue', 'summary'],
        num_rows: 14732
    })
    test: Dataset({
        features: ['id', 'dialogue', 'summary'],
        num_rows: 819
    })
    validation: Dataset({
        features: ['id', 'dialogue', 'summary'],
        num_rows: 818
    })
})

In [18]:
from datasets import load_dataset

dataset_billsum = load_dataset("FiscalNote/billsum")

print(dataset_billsum)

README.md:   0%|          | 0.00/7.27k [00:00<?, ?B/s]

data/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 91.8MB

data/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

data/test-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 15.8MB

data/test-00000-of-00001.parquet: downloading bytes:           |  0.00B

data/ca_test-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 6.12MB

data/ca_test-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/18949 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/3269 [00:00<?, ? examples/s]

Generating ca_test split:   0%|          | 0/1237 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['text', 'summary', 'title'],
        num_rows: 18949
    })
    test: Dataset({
        features: ['text', 'summary', 'title'],
        num_rows: 3269
    })
    ca_test: Dataset({
        features: ['text', 'summary', 'title'],
        num_rows: 1237
    })
})

In [19]:
print(dataset_billsum["train"].column_names)

['text', 'summary', 'title']

In [20]:
print("LEGAL DOCUMENT:")
print(dataset_billsum["train"][0]["text"])

print("\nSUMMARY:")
print(dataset_billsum["train"][0]["summary"])

LEGAL DOCUMENT:
SECTION 1. LIABILITY OF BUSINESS ENTITIES PROVIDING USE OF FACILITIES
              TO NONPROFIT ORGANIZATIONS.

    (a) Definitions.--In this section:
            (1) Business entity.--The term ``business entity'' means a
        firm, corporation, association, partnership, consortium, joint
        venture, or other form of enterprise.
            (2) Facility.--The term ``facility'' means any real
        property, including any building, improvement, or appurtenance.
            (3) Gross negligence.--The term ``gross negligence'' means
        voluntary and conscious conduct by a person with knowledge (at
        the time of the conduct) that the conduct is likely to be
        harmful to the health or well-being of another person.
            (4) Intentional misconduct.--The term ``intentional
        misconduct'' means conduct by a person with knowledge (at the
        time of the conduct) that the conduct is harmful to the health
        or well-being of another person.
            (5) Nonprofit organization.--The term ``nonprofit
        organization'' means--
                    (A) any organization described in section 501(c)(3)
                of the Internal Revenue Code of 1986 and exempt from
                tax under section 501(a) of such Code; or
                    (B) any not-for-profit organization organized and
                conducted for public benefit and operated primarily for
                charitable, civic, educational, religious, welfare, or
                health purposes.
            (6) State.--The term ``State'' means each of the several
        States, the District of Columbia, the Commonwealth of Puerto
        Rico, the Virgin Islands, Guam, American Samoa, the Northern
        Mariana Islands, any other territory or possession of the
        United States, or any political subdivision of any such State,
        territory, or possession.
    (b) Limitation on Liability.--
            (1) In general.--Subject to subsection (c), a business
        entity shall not be subject to civil liability relating to any
        injury or death occurring at a facility of the business entity
        in connection with a use of such facility by a nonprofit
        organization if--
                    (A) the use occurs outside of the scope of business
                of the business entity;
                    (B) such injury or death occurs during a period
                that such facility is used by the nonprofit
                organization; and
                    (C) the business entity authorized the use of such
                facility by the nonprofit organization.
            (2) Application.--This subsection shall apply--
                    (A) with respect to civil liability under Federal
                and State law; and
                    (B) regardless of whether a nonprofit organization
                pays for the use of a facility.
    (c) Exception for Liability.--Subsection (b) shall not apply to an
injury or death that results from an act or omission of a business
entity that constitutes gross negligence or intentional misconduct,
including any misconduct that--
            (1) constitutes a crime of violence (as that term is
        defined in section 16 of title 18, United States Code) or act
        of international terrorism (as that term is defined in section
        2331 of title 18) for which the defendant has been convicted in
        any court;
            (2) constitutes a hate crime (as that term is used in the
        Hate Crime Statistics Act (28 U.S.C. 534 note));
            (3) involves a sexual offense, as defined by applicable
        State law, for which the defendant has been convicted in any
        court; or
            (4) involves misconduct for which the defendant has been
        found to have violated a Federal or State civil rights law.
    (d) Superseding Provision.--
            (1) In general.--Subject to paragraph (2) and subsection
        (e), this Act preempts the laws of any State to the extent that
        such laws are inconsistent with this Act, except that this Act
        shall not preempt any State law that provides additional
        protection from liability for a business entity for an injury
        or death with respect to which conditions under subparagraphs
        (A) through (C) of subsection (b)(1) apply.
            (2) Limitation.--Nothing in this Act shall be construed to
        supersede any Federal or State health or safety law.
    (e) Election of State Regarding Nonapplicability.--This Act shall
not apply to any civil action in a State court against a business
entity in which all parties are citizens of the State if such State
enacts a statute--
            (1) citing the authority of this subsection;
            (2) declaring the election of such State that this Act
        shall not apply to such civil action in the State; and
            (3) containing no other provision.

SUMMARY:
Shields a business entity from civil liability relating to any injury or death occurring at a facility of that entity in connection with a use of such facility by a nonprofit organization if: (1) the use occurs outside the scope of business of the business entity; (2) such injury or death occurs during a period that such facility is used by such organization; and (3) the business entity authorized the use of such facility by the organization.
Makes this Act inapplicable to an injury or death that results from an act or omission of a business entity that constitutes gross negligence or intentional misconduct, including misconduct that: (1) constitutes a hate crime or a crime of violence or act of international terrorism for which the defendant has been convicted in any court; or (2) involves a sexual offense for which the defendant has been convicted in any court or misconduct for which the defendant has been found to have violated a Federal or State civil rights law.
Preempts State laws to the extent that such laws are inconsistent with this Act, except State law that provides additional protection from liability.  Specifies that this Act shall not be construed to supersede any Federal or State health or safety law.
Makes this Act inapplicable to any civil action in a State court against a business entity in which all parties are citizens of the State if such State, citing this Act's authority and containing no other provision, enacts a statute declaring the State's election that this Act shall not apply to such action in the State.

In [23]:
model_ckpt = "facebook/bart-large-cnn"

In [24]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

tokenizer = AutoTokenizer.from_pretrained(model_ckpt)

model_bart = AutoModelForSeq2SeqLM.from_pretrained(model_ckpt).to(device)

config.json:   0%|          | 0.00/1.58k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.63GB

model.safetensors: downloading bytes:           |  0.00B

[transformers] Please make sure the generation config includes `forced_bos_token_id=0`.

Loading weights:   0%|          | 0/511 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

In [2]:
from datasets import load_dataset

dataset_billsum = load_dataset("FiscalNote/billsum")

dataset_billsum

README.md:   0%|          | 0.00/7.27k [00:00<?, ?B/s]

data/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 91.8MB

data/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

data/test-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 15.8MB

data/test-00000-of-00001.parquet: downloading bytes:           |  0.00B

data/ca_test-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 6.12MB

data/ca_test-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/18949 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/3269 [00:00<?, ? examples/s]

Generating ca_test split:   0%|          | 0/1237 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['text', 'summary', 'title'],
        num_rows: 18949
    })
    test: Dataset({
        features: ['text', 'summary', 'title'],
        num_rows: 3269
    })
    ca_test: Dataset({
        features: ['text', 'summary', 'title'],
        num_rows: 1237
    })
})

In [3]:
print(dataset_billsum)

DatasetDict({
    train: Dataset({
        features: ['text', 'summary', 'title'],
        num_rows: 18949
    })
    test: Dataset({
        features: ['text', 'summary', 'title'],
        num_rows: 3269
    })
    ca_test: Dataset({
        features: ['text', 'summary', 'title'],
        num_rows: 1237
    })
})

In [4]:
print(dataset_billsum["train"].column_names)

['text', 'summary', 'title']

In [5]:
print("LEGAL DOCUMENT:")
print(dataset_billsum["train"][0]["text"])

print("\nSUMMARY:")
print(dataset_billsum["train"][0]["summary"])

LEGAL DOCUMENT:
SECTION 1. LIABILITY OF BUSINESS ENTITIES PROVIDING USE OF FACILITIES
              TO NONPROFIT ORGANIZATIONS.

    (a) Definitions.--In this section:
            (1) Business entity.--The term ``business entity'' means a
        firm, corporation, association, partnership, consortium, joint
        venture, or other form of enterprise.
            (2) Facility.--The term ``facility'' means any real
        property, including any building, improvement, or appurtenance.
            (3) Gross negligence.--The term ``gross negligence'' means
        voluntary and conscious conduct by a person with knowledge (at
        the time of the conduct) that the conduct is likely to be
        harmful to the health or well-being of another person.
            (4) Intentional misconduct.--The term ``intentional
        misconduct'' means conduct by a person with knowledge (at the
        time of the conduct) that the conduct is harmful to the health
        or well-being of another person.
            (5) Nonprofit organization.--The term ``nonprofit
        organization'' means--
                    (A) any organization described in section 501(c)(3)
                of the Internal Revenue Code of 1986 and exempt from
                tax under section 501(a) of such Code; or
                    (B) any not-for-profit organization organized and
                conducted for public benefit and operated primarily for
                charitable, civic, educational, religious, welfare, or
                health purposes.
            (6) State.--The term ``State'' means each of the several
        States, the District of Columbia, the Commonwealth of Puerto
        Rico, the Virgin Islands, Guam, American Samoa, the Northern
        Mariana Islands, any other territory or possession of the
        United States, or any political subdivision of any such State,
        territory, or possession.
    (b) Limitation on Liability.--
            (1) In general.--Subject to subsection (c), a business
        entity shall not be subject to civil liability relating to any
        injury or death occurring at a facility of the business entity
        in connection with a use of such facility by a nonprofit
        organization if--
                    (A) the use occurs outside of the scope of business
                of the business entity;
                    (B) such injury or death occurs during a period
                that such facility is used by the nonprofit
                organization; and
                    (C) the business entity authorized the use of such
                facility by the nonprofit organization.
            (2) Application.--This subsection shall apply--
                    (A) with respect to civil liability under Federal
                and State law; and
                    (B) regardless of whether a nonprofit organization
                pays for the use of a facility.
    (c) Exception for Liability.--Subsection (b) shall not apply to an
injury or death that results from an act or omission of a business
entity that constitutes gross negligence or intentional misconduct,
including any misconduct that--
            (1) constitutes a crime of violence (as that term is
        defined in section 16 of title 18, United States Code) or act
        of international terrorism (as that term is defined in section
        2331 of title 18) for which the defendant has been convicted in
        any court;
            (2) constitutes a hate crime (as that term is used in the
        Hate Crime Statistics Act (28 U.S.C. 534 note));
            (3) involves a sexual offense, as defined by applicable
        State law, for which the defendant has been convicted in any
        court; or
            (4) involves misconduct for which the defendant has been
        found to have violated a Federal or State civil rights law.
    (d) Superseding Provision.--
            (1) In general.--Subject to paragraph (2) and subsection
        (e), this Act preempts the laws of any State to the extent that
        such laws are inconsistent with this Act, except that this Act
        shall not preempt any State law that provides additional
        protection from liability for a business entity for an injury
        or death with respect to which conditions under subparagraphs
        (A) through (C) of subsection (b)(1) apply.
            (2) Limitation.--Nothing in this Act shall be construed to
        supersede any Federal or State health or safety law.
    (e) Election of State Regarding Nonapplicability.--This Act shall
not apply to any civil action in a State court against a business
entity in which all parties are citizens of the State if such State
enacts a statute--
            (1) citing the authority of this subsection;
            (2) declaring the election of such State that this Act
        shall not apply to such civil action in the State; and
            (3) containing no other provision.

SUMMARY:
Shields a business entity from civil liability relating to any injury or death occurring at a facility of that entity in connection with a use of such facility by a nonprofit organization if: (1) the use occurs outside the scope of business of the business entity; (2) such injury or death occurs during a period that such facility is used by such organization; and (3) the business entity authorized the use of such facility by the organization.
Makes this Act inapplicable to an injury or death that results from an act or omission of a business entity that constitutes gross negligence or intentional misconduct, including misconduct that: (1) constitutes a hate crime or a crime of violence or act of international terrorism for which the defendant has been convicted in any court; or (2) involves a sexual offense for which the defendant has been convicted in any court or misconduct for which the defendant has been found to have violated a Federal or State civil rights law.
Preempts State laws to the extent that such laws are inconsistent with this Act, except State law that provides additional protection from liability.  Specifies that this Act shall not be construed to supersede any Federal or State health or safety law.
Makes this Act inapplicable to any civil action in a State court against a business entity in which all parties are citizens of the State if such State, citing this Act's authority and containing no other provision, enacts a statute declaring the State's election that this Act shall not apply to such action in the State.

In [6]:
def convert_examples_to_features(example_batch):
    input_encodings = tokenizer(
        example_batch["text"],
        max_length=1024,
        truncation=True
    )

    target_encodings = tokenizer(
        text_target=example_batch["summary"],
        max_length=128,
        truncation=True
    )

    return {
        "input_ids": input_encodings["input_ids"],
        "attention_mask": input_encodings["attention_mask"],
        "labels": target_encodings["input_ids"]
    }

In [7]:
if 'tokenizer' not in globals():
    from transformers import AutoTokenizer
    model_ckpt = "facebook/bart-large-cnn"
    tokenizer = AutoTokenizer.from_pretrained(model_ckpt)

tokenized_dataset = dataset_billsum.map(
    convert_examples_to_features,
    batched=True
)

Map:   0%|          | 0/18949 [00:00<?, ? examples/s]

NameError: name 'tokenizer' is not defined

In [8]:
from transformers import AutoTokenizer

model_ckpt = "facebook/bart-large-cnn"

tokenizer = AutoTokenizer.from_pretrained(model_ckpt)

config.json:   0%|          | 0.00/1.58k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

In [9]:
print(tokenizer)

RobertaTokenizer(name_or_path='facebook/bart-large-cnn', vocab_size=50265, model_max_length=1000000000000000019884624838656, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<s>', 'eos_token': '</s>', 'unk_token': '<unk>', 'sep_token': '</s>', 'pad_token': '<pad>', 'cls_token': '<s>', 'mask_token': '<mask>'}, added_tokens_decoder={
	0: AddedToken("<s>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
	1: AddedToken("<pad>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
	2: AddedToken("</s>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
	3: AddedToken("<unk>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),
	50264: AddedToken("<mask>", rstrip=False, lstrip=True, single_word=False, normalized=True, special=True),
})

In [10]:
def convert_examples_to_features(example_batch):
    input_encodings = tokenizer(
        example_batch["text"],
        max_length=1024,
        truncation=True
    )

    target_encodings = tokenizer(
        text_target=example_batch["summary"],
        max_length=128,
        truncation=True
    )

    return {
        "input_ids": input_encodings["input_ids"],
        "attention_mask": input_encodings["attention_mask"],
        "labels": target_encodings["input_ids"]
    }

In [11]:
tokenized_dataset = dataset_billsum.map(
    convert_examples_to_features,
    batched=True
)

Map:   0%|          | 0/18949 [00:00<?, ? examples/s]

Map:   0%|          | 0/3269 [00:00<?, ? examples/s]

Map:   0%|          | 0/1237 [00:00<?, ? examples/s]

In [12]:
print(tokenized_dataset)

DatasetDict({
    train: Dataset({
        features: ['text', 'summary', 'title', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 18949
    })
    test: Dataset({
        features: ['text', 'summary', 'title', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 3269
    })
    ca_test: Dataset({
        features: ['text', 'summary', 'title', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 1237
    })
})

In [13]:
print(tokenized_dataset["train"][0].keys())

dict_keys(['text', 'summary', 'title', 'input_ids', 'attention_mask', 'labels'])

In [14]:
print(len(tokenized_dataset["train"]))
print(len(tokenized_dataset["test"]))
print(len(tokenized_dataset["validation"]))

18949
3269

KeyError: 'validation'

In [15]:
print(tokenized_dataset)

DatasetDict({
    train: Dataset({
        features: ['text', 'summary', 'title', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 18949
    })
    test: Dataset({
        features: ['text', 'summary', 'title', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 3269
    })
    ca_test: Dataset({
        features: ['text', 'summary', 'title', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 1237
    })
})

In [16]:
print(tokenized_dataset.keys())

dict_keys(['train', 'test', 'ca_test'])

In [17]:
print("Train:", len(tokenized_dataset["train"]))
print("Test:", len(tokenized_dataset["test"]))
print("California Test:", len(tokenized_dataset["ca_test"]))

Train: 18949
Test: 3269
California Test: 1237

In [19]:
from transformers import DataCollatorForSeq2Seq

seq2seq_data_collator = DataCollatorForSeq2Seq(
    tokenizer=tokenizer,
    model=model_bart
)

NameError: name 'model_bart' is not defined

In [20]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

model_ckpt = "facebook/bart-large-cnn"

tokenizer = AutoTokenizer.from_pretrained(model_ckpt)

model_bart = AutoModelForSeq2SeqLM.from_pretrained(model_ckpt).to(device)

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.63GB

model.safetensors: downloading bytes:           |  0.00B

[transformers] Please make sure the generation config includes `forced_bos_token_id=0`.

Loading weights:   0%|          | 0/511 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

NameError: name 'device' is not defined

In [21]:
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"

print("Device:", device)

Device: cuda

In [22]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

model_ckpt = "facebook/bart-large-cnn"

tokenizer = AutoTokenizer.from_pretrained(model_ckpt)

model_bart = AutoModelForSeq2SeqLM.from_pretrained(model_ckpt).to(device)

Loading weights:   0%|          | 0/511 [00:00<?, ?it/s]

In [23]:
print(type(model_bart))
print(device)

<class 'transformers.models.bart.modeling_bart.BartForConditionalGeneration'>
cuda

In [24]:
from transformers import DataCollatorForSeq2Seq

seq2seq_data_collator = DataCollatorForSeq2Seq(
    tokenizer=tokenizer,
    model=model_bart
)

In [25]:
from transformers import Seq2SeqTrainingArguments

training_args = Seq2SeqTrainingArguments(
    output_dir="./bart-billsum",
    num_train_epochs=1,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=4,
    warmup_steps=500,
    weight_decay=0.01,
    logging_steps=100,
    save_steps=500,
    save_total_limit=2,
    fp16=True,
    report_to="none"
)

In [26]:
from datasets import DatasetDict

split_dataset = tokenized_dataset["train"].train_test_split(
    test_size=0.1,
    seed=42
)

tokenized_dataset = DatasetDict({
    "train": split_dataset["train"],
    "validation": split_dataset["test"],
    "test": tokenized_dataset["test"],
    "ca_test": tokenized_dataset["ca_test"]
})

print(tokenized_dataset)

DatasetDict({
    train: Dataset({
        features: ['text', 'summary', 'title', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 17054
    })
    validation: Dataset({
        features: ['text', 'summary', 'title', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 1895
    })
    test: Dataset({
        features: ['text', 'summary', 'title', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 3269
    })
    ca_test: Dataset({
        features: ['text', 'summary', 'title', 'input_ids', 'attention_mask', 'labels'],
        num_rows: 1237
    })
})

In [28]:
from transformers import DataCollatorForSeq2Seq

seq2seq_data_collator = DataCollatorForSeq2Seq(
    tokenizer=tokenizer,
    model=model_bart
)

In [29]:
from transformers import Seq2SeqTrainingArguments

training_args = Seq2SeqTrainingArguments(
    output_dir="./bart-billsum",
    num_train_epochs=1,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=4,
    warmup_steps=500,
    weight_decay=0.01,
    logging_steps=100,
    evaluation_strategy="steps",
    eval_steps=500,
    save_steps=500,
    save_total_limit=2,
    fp16=True,
    predict_with_generate=True,
    report_to="none"
)

TypeError: Seq2SeqTrainingArguments.__init__() got an unexpected keyword argument 'evaluation_strategy'

In [30]:
from transformers import Seq2SeqTrainingArguments

training_args = Seq2SeqTrainingArguments(
    output_dir="./bart-billsum",
    num_train_epochs=1,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=4,
    warmup_steps=500,
    weight_decay=0.01,
    logging_steps=100,
    eval_strategy="steps",
    eval_steps=500,
    save_steps=500,
    save_total_limit=2,
    fp16=True,
    predict_with_generate=True,
    report_to="none"
)

In [31]:
from transformers import Seq2SeqTrainer

trainer = Seq2SeqTrainer(
    model=model_bart,
    args=training_args,
    processing_class=tokenizer,
    data_collator=seq2seq_data_collator,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["validation"]
)

In [32]:
print(tokenized_dataset.keys())

dict_keys(['train', 'validation', 'test', 'ca_test'])

In [33]:
from transformers import Seq2SeqTrainer

trainer = Seq2SeqTrainer(
    model=model_bart,
    args=training_args,
    processing_class=tokenizer,
    data_collator=seq2seq_data_collator,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["validation"]
)

In [34]:
print(trainer)

<transformers.trainer_seq2seq.Seq2SeqTrainer object at 0x7f124356ee90>

In [35]:
trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=4264, training_loss=5.949751862889159, metrics={'train_runtime': 4684.0579, 'train_samples_per_second': 3.641, 'train_steps_per_second': 0.91, 'total_flos': 3.695780188441805e+16, 'train_loss': 5.949751862889159, 'epoch': 1.0})

In [36]:
print(trainer.state)

TrainerState(epoch=1.0, global_step=4264, max_steps=4264, logging_steps=100, eval_steps=500, save_steps=500, train_batch_size=1, num_train_epochs=1, num_input_tokens_seen=0, total_flos=3.695780188441805e+16, log_history=[{'loss': 8.78609130859375, 'grad_norm': 21.129344940185547, 'learning_rate': 9.900000000000002e-06, 'epoch': 0.023454907939486336, 'step': 100}, {'loss': 7.295335083007813, 'grad_norm': 27.29916763305664, 'learning_rate': 1.9900000000000003e-05, 'epoch': 0.04690981587897267, 'step': 200}, {'loss': 7.083353271484375, 'grad_norm': 23.87660789489746, 'learning_rate': 2.9900000000000002e-05, 'epoch': 0.07036472381845901, 'step': 300}, {'loss': 6.996622314453125, 'grad_norm': 22.891468048095703, 'learning_rate': 3.99e-05, 'epoch': 0.09381963175794535, 'step': 400}, {'loss': 6.826831665039062, 'grad_norm': 23.813791275024414, 'learning_rate': 4.99e-05, 'epoch': 0.11727453969743169, 'step': 500}, {'eval_loss': 1.6989282369613647, 'eval_runtime': 95.1808, 'eval_samples_per_second': 19.909, 'eval_steps_per_second': 19.909, 'epoch': 0.11727453969743169, 'step': 500}, {'loss': 6.803872680664062, 'grad_norm': 20.1434268951416, 'learning_rate': 4.868490967056323e-05, 'epoch': 0.14072944763691803, 'step': 600}, {'loss': 6.67129638671875, 'grad_norm': 23.417726516723633, 'learning_rate': 4.735653560042509e-05, 'epoch': 0.16418435557640437, 'step': 700}, {'loss': 6.62468017578125, 'grad_norm': 22.24662208557129, 'learning_rate': 4.602816153028693e-05, 'epoch': 0.1876392635158907, 'step': 800}, {'loss': 6.5753851318359375, 'grad_norm': 18.932153701782227, 'learning_rate': 4.469978746014878e-05, 'epoch': 0.21109417145537704, 'step': 900}, {'loss': 6.59165771484375, 'grad_norm': 24.7999324798584, 'learning_rate': 4.337141339001063e-05, 'epoch': 0.23454907939486339, 'step': 1000}, {'eval_loss': 1.5841623544692993, 'eval_runtime': 95.1024, 'eval_samples_per_second': 19.926, 'eval_steps_per_second': 19.926, 'epoch': 0.23454907939486339, 'step': 1000}, {'loss': 6.4155615234375, 'grad_norm': 17.874252319335938, 'learning_rate': 4.204303931987248e-05, 'epoch': 0.2580039873343497, 'step': 1100}, {'loss': 6.421626586914062, 'grad_norm': 18.990291595458984, 'learning_rate': 4.071466524973433e-05, 'epoch': 0.28145889527383605, 'step': 1200}, {'loss': 6.49125732421875, 'grad_norm': 18.28975486755371, 'learning_rate': 3.9386291179596174e-05, 'epoch': 0.3049138032133224, 'step': 1300}, {'loss': 6.09428466796875, 'grad_norm': 25.98996925354004, 'learning_rate': 3.805791710945802e-05, 'epoch': 0.32836871115280875, 'step': 1400}, {'loss': 5.948995361328125, 'grad_norm': 20.45863151550293, 'learning_rate': 3.672954303931987e-05, 'epoch': 0.35182361909229504, 'step': 1500}, {'eval_loss': 1.4997012615203857, 'eval_runtime': 95.3549, 'eval_samples_per_second': 19.873, 'eval_steps_per_second': 19.873, 'epoch': 0.35182361909229504, 'step': 1500}, {'loss': 6.032526245117188, 'grad_norm': 19.066919326782227, 'learning_rate': 3.540116896918173e-05, 'epoch': 0.3752785270317814, 'step': 1600}, {'loss': 5.919320678710937, 'grad_norm': 22.329532623291016, 'learning_rate': 3.407279489904357e-05, 'epoch': 0.39873343497126773, 'step': 1700}, {'loss': 5.855436401367188, 'grad_norm': 16.14894676208496, 'learning_rate': 3.274442082890542e-05, 'epoch': 0.4221883429107541, 'step': 1800}, {'loss': 5.7392529296875, 'grad_norm': 20.159513473510742, 'learning_rate': 3.141604675876727e-05, 'epoch': 0.4456432508502404, 'step': 1900}, {'loss': 5.685411376953125, 'grad_norm': 40.34056854248047, 'learning_rate': 3.008767268862912e-05, 'epoch': 0.46909815878972677, 'step': 2000}, {'eval_loss': 1.4282032251358032, 'eval_runtime': 94.687, 'eval_samples_per_second': 20.013, 'eval_steps_per_second': 20.013, 'epoch': 0.46909815878972677, 'step': 2000}, {'loss': 5.885484619140625, 'grad_norm': 20.565673828125, 'learning_rate': 2.875929861849097e-05, 'epoch': 0.49255306672921306, 'step': 2100}, {'loss': 5.6903228759765625, 'grad_norm': 19.7473087310791, 'learning_rate': 2.7430924548352817e-05, 'epoch': 0.5160079746686994, 'step': 2200}, {'loss': 5.7018359375, 'grad_norm': 20.660144805908203, 'learning_rate': 2.6102550478214666e-05, 'epoch': 0.5394628826081858, 'step': 2300}, {'loss': 5.7494677734375, 'grad_norm': 16.530025482177734, 'learning_rate': 2.4774176408076515e-05, 'epoch': 0.5629177905476721, 'step': 2400}, {'loss': 5.595919189453125, 'grad_norm': 15.54459285736084, 'learning_rate': 2.3445802337938364e-05, 'epoch': 0.5863726984871585, 'step': 2500}, {'eval_loss': 1.4138528108596802, 'eval_runtime': 94.4062, 'eval_samples_per_second': 20.073, 'eval_steps_per_second': 20.073, 'epoch': 0.5863726984871585, 'step': 2500}, {'loss': 5.9242010498046875, 'grad_norm': 16.09828758239746, 'learning_rate': 2.2117428267800213e-05, 'epoch': 0.6098276064266448, 'step': 2600}, {'loss': 5.527216186523438, 'grad_norm': 18.192014694213867, 'learning_rate': 2.0789054197662065e-05, 'epoch': 0.6332825143661311, 'step': 2700}, {'loss': 5.483729248046875, 'grad_norm': 19.802053451538086, 'learning_rate': 1.946068012752391e-05, 'epoch': 0.6567374223056175, 'step': 2800}, {'loss': 5.348513793945313, 'grad_norm': 19.452800750732422, 'learning_rate': 1.8132306057385763e-05, 'epoch': 0.6801923302451038, 'step': 2900}, {'loss': 5.4368353271484375, 'grad_norm': 15.873720169067383, 'learning_rate': 1.680393198724761e-05, 'epoch': 0.7036472381845901, 'step': 3000}, {'eval_loss': 1.342374563217163, 'eval_runtime': 95.5706, 'eval_samples_per_second': 19.828, 'eval_steps_per_second': 19.828, 'epoch': 0.7036472381845901, 'step': 3000}, {'loss': 5.36596435546875, 'grad_norm': 13.699777603149414, 'learning_rate': 1.547555791710946e-05, 'epoch': 0.7271021461240764, 'step': 3100}, {'loss': 5.205662841796875, 'grad_norm': 17.851051330566406, 'learning_rate': 1.4147183846971306e-05, 'epoch': 0.7505570540635628, 'step': 3200}, {'loss': 5.404370727539063, 'grad_norm': 19.296253204345703, 'learning_rate': 1.2818809776833157e-05, 'epoch': 0.7740119620030491, 'step': 3300}, {'loss': 5.061900634765625, 'grad_norm': 18.380102157592773, 'learning_rate': 1.1490435706695006e-05, 'epoch': 0.7974668699425355, 'step': 3400}, {'loss': 5.260396728515625, 'grad_norm': 15.697425842285156, 'learning_rate': 1.0162061636556855e-05, 'epoch': 0.8209217778820218, 'step': 3500}, {'eval_loss': 1.323378086090088, 'eval_runtime': 95.7157, 'eval_samples_per_second': 19.798, 'eval_steps_per_second': 19.798, 'epoch': 0.8209217778820218, 'step': 3500}, {'loss': 5.279055786132813, 'grad_norm': 16.831314086914062, 'learning_rate': 8.833687566418703e-06, 'epoch': 0.8443766858215082, 'step': 3600}, {'loss': 5.435071411132813, 'grad_norm': 15.936113357543945, 'learning_rate': 7.505313496280552e-06, 'epoch': 0.8678315937609945, 'step': 3700}, {'loss': 5.31252197265625, 'grad_norm': 17.514646530151367, 'learning_rate': 6.176939426142402e-06, 'epoch': 0.8912865017004808, 'step': 3800}, {'loss': 5.1002413940429685, 'grad_norm': 15.200799942016602, 'learning_rate': 4.848565356004251e-06, 'epoch': 0.9147414096399672, 'step': 3900}, {'loss': 5.250459594726562, 'grad_norm': 16.858430862426758, 'learning_rate': 3.5201912858661e-06, 'epoch': 0.9381963175794535, 'step': 4000}, {'eval_loss': 1.2946231365203857, 'eval_runtime': 95.7132, 'eval_samples_per_second': 19.799, 'eval_steps_per_second': 19.799, 'epoch': 0.9381963175794535, 'step': 4000}, {'loss': 5.141063842773438, 'grad_norm': 21.83603858947754, 'learning_rate': 2.1918172157279492e-06, 'epoch': 0.9616512255189399, 'step': 4100}, {'loss': 5.335498046875, 'grad_norm': 12.722994804382324, 'learning_rate': 8.634431455897981e-07, 'epoch': 0.9851061334584261, 'step': 4200}, {'eval_loss': 1.2932058572769165, 'eval_runtime': 95.406, 'eval_samples_per_second': 19.862, 'eval_steps_per_second': 19.862, 'epoch': 1.0, 'step': 4264}, {'train_runtime': 4684.0579, 'train_samples_per_second': 3.641, 'train_steps_per_second': 0.91, 'total_flos': 3.695780188441805e+16, 'train_loss': 5.949751862889159, 'epoch': 1.0, 'step': 4264}], best_metric=None, best_global_step=None, best_model_checkpoint=None, is_local_process_zero=True, is_world_process_zero=True, is_hyper_param_search=False, trial_name=None, trial_params=None, stateful_callbacks={'TrainerControl': {'args': {'should_training_stop': True, 'should_epoch_stop': False, 'should_save': True, 'should_evaluate': False, 'should_log': False}, 'attributes': {}}})

In [1]:
!pip install -q evaluate
import evaluate
import torch
from tqdm.auto import tqdm

rouge = evaluate.load("rouge")

print("ROUGE loaded successfully")

ModuleNotFoundError: No module named 'evaluate'

In [2]:
!pip install -q

ERROR: You must give at least one requirement to install (see "pip help install")

In [3]:
!pip install -q evaluate rouge_score

  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 2.8 MB/s eta 0:00:00
  Building wheel for rouge_score (setup.py) ... done

In [4]:
import evaluate
import torch
from tqdm.auto import tqdm

rouge = evaluate.load("rouge")

print("ROUGE loaded successfully")

Downloading builder script: 0.00B [00:00, ?B/s]

ROUGE loaded successfully

In [5]:
def calculate_metric_on_test_ds(
    dataset,
    metric,
    model,
    tokenizer,
    batch_size=2,
    device=None,
    column_text="text",
    column_summary="summary"
):
    if device is None:
        device = "cuda" if torch.cuda.is_available() else "cpu"

    model.eval()

    predictions = []
    references = []

    for start in tqdm(range(0, len(dataset), batch_size)):
        end = min(start + batch_size, len(dataset))
        batch = dataset[start:end]

        # Tokenize legal documents
        inputs = tokenizer(
            batch[column_text],
            max_length=1024,
            truncation=True,
            padding=True,
            return_tensors="pt"
        )

        inputs = {
            key: value.to(device)
            for key, value in inputs.items()
        }

        # Generate summaries
        with torch.no_grad():
            summaries = model.generate(
                input_ids=inputs["input_ids"],
                attention_mask=inputs["attention_mask"],
                max_new_tokens=128,
                num_beams=4,
                early_stopping=True
            )

        # Convert generated tokens back to text
        decoded_summaries = tokenizer.batch_decode(
            summaries,
            skip_special_tokens=True,
            clean_up_tokenization_spaces=True
        )

        predictions.extend(decoded_summaries)
        references.extend(batch[column_summary])

    # Calculate ROUGE scores
    scores = metric.compute(
        predictions=predictions,
        references=references,
        use_stemmer=True
    )

    return scores

NameError: name 'device' is not defined

In [6]:
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"

print("Device:", device)

Device: cpu

In [7]:
if 'tokenized_dataset' not in globals():
    from datasets import load_dataset
    from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
    import torch

    # 1. Load dataset
    dataset_billsum = load_dataset("FiscalNote/billsum")

    # 2. Load model and tokenizer
    model_ckpt = "facebook/bart-large-cnn"
    tokenizer = AutoTokenizer.from_pretrained(model_ckpt)
    device = "cuda" if torch.cuda.is_available() else "cpu"
    model_bart = AutoModelForSeq2SeqLM.from_pretrained(model_ckpt).to(device)

    # 3. Tokenize
    def convert_examples_to_features(example_batch):
        input_encodings = tokenizer(example_batch["text"], max_length=1024, truncation=True)
        target_encodings = tokenizer(text_target=example_batch["summary"], max_length=128, truncation=True)
        return {
            "input_ids": input_encodings["input_ids"],
            "attention_mask": input_encodings["attention_mask"],
            "labels": target_encodings["input_ids"]
        }
    tokenized_dataset = dataset_billsum.map(convert_examples_to_features, batched=True)

test_sample = tokenized_dataset["test"].select(range(100))

rouge_scores = calculate_metric_on_test_ds(
    dataset=test_sample,
    metric=rouge,
    model=model_bart,
    tokenizer=tokenizer,
    batch_size=2,
    device=device,
    column_text="text",
    column_summary="summary"
)

print(rouge_scores)

NameError: name 'tokenized_dataset' is not defined

In [8]:
import torch
import os

print("GPU available:", torch.cuda.is_available())
print("Device:", "cuda" if torch.cuda.is_available() else "cpu")

print("Tokenized dataset exists:", "tokenized_dataset" in globals())
print("BART model exists:", "model_bart" in globals())

checkpoint_dir = "/content/bart-billsum"
print("Training output folder exists:", os.path.exists(checkpoint_dir))

if os.path.exists(checkpoint_dir):
    print("Files:", os.listdir(checkpoint_dir))

GPU available: False
Device: cpu
Tokenized dataset exists: False
BART model exists: False
Training output folder exists: False

In [1]:
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"
print("GPU available:", torch.cuda.is_available())
print("Device:", device)

GPU available: True
Device: cuda

In [2]:
from google.colab import drive

drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
import os

for root, dirs, files in os.walk("/content/drive/MyDrive"):
    if "bart-billsum" in dirs:
        print("Found model folder:", os.path.join(root, "bart-billsum"))

In [4]:
import os

model_folders = []

for root, dirs, files in os.walk("/content/drive/MyDrive"):
    if (
        "config.json" in files
        and (
            "model.safetensors" in files
            or "pytorch_model.bin" in files
        )
    ):
        model_folders.append(root)

print("Saved model folders:")
for folder in model_folders:
    print(folder)

Saved model folders:

In [5]:
from google.colab import drive

drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [6]:
import os

output_dir = "/content/drive/MyDrive/Text-Summarizer/bart-billsum"

os.makedirs(output_dir, exist_ok=True)

print("Model will be saved to:", output_dir)

Model will be saved to: /content/drive/MyDrive/Text-Summarizer/bart-billsum

In [7]:
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

Device: cuda

In [8]:
from transformers import Seq2SeqTrainingArguments

training_args = Seq2SeqTrainingArguments(
    output_dir=output_dir,
    num_train_epochs=1,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=4,
    warmup_steps=500,
    weight_decay=0.01,
    logging_steps=100,
    eval_strategy="steps",
    eval_steps=500,
    save_strategy="steps",
    save_steps=500,
    save_total_limit=2,
    fp16=torch.cuda.is_available(),
    predict_with_generate=True,
    report_to="none"
)

In [9]:
if 'trainer' not in globals():
    from datasets import load_dataset, DatasetDict
    from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, DataCollatorForSeq2Seq, Seq2SeqTrainer, Seq2SeqTrainingArguments
    import torch

    print("Initializing all components for training...")

    # 1. Device and Model setup
    device = "cuda" if torch.cuda.is_available() else "cpu"
    model_ckpt = "facebook/bart-large-cnn"
    tokenizer = AutoTokenizer.from_pretrained(model_ckpt)
    model_bart = AutoModelForSeq2SeqLM.from_pretrained(model_ckpt).to(device)

    # 2. Dataset loading and processing
    dataset_billsum = load_dataset("FiscalNote/billsum")
    def convert_examples_to_features(example_batch):
        input_encodings = tokenizer(example_batch["text"], max_length=1024, truncation=True)
        target_encodings = tokenizer(text_target=example_batch["summary"], max_length=128, truncation=True)
        return {
            "input_ids": input_encodings["input_ids"],
            "attention_mask": input_encodings["attention_mask"],
            "labels": target_encodings["input_ids"]
        }
    tokenized_dataset = dataset_billsum.map(convert_examples_to_features, batched=True)

    # Train-test split for validation
    split_dataset = tokenized_dataset["train"].train_test_split(test_size=0.1, seed=42)
    tokenized_dataset = DatasetDict({
        "train": split_dataset["train"],
        "validation": split_dataset["test"],
        "test": tokenized_dataset["test"],
        "ca_test": tokenized_dataset["ca_test"]
    })

    # 3. Data collator
    seq2seq_data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=model_bart)

    # 4. Training Arguments
    if 'training_args' not in globals():
        output_dir = "/content/drive/MyDrive/Text-Summarizer/bart-billsum"
        training_args = Seq2SeqTrainingArguments(
            output_dir=output_dir,
            num_train_epochs=1,
            per_device_train_batch_size=1,
            per_device_eval_batch_size=1,
            gradient_accumulation_steps=4,
            warmup_steps=500,
            weight_decay=0.01,
            logging_steps=100,
            eval_strategy="steps",
            eval_steps=500,
            save_strategy="steps",
            save_steps=500,
            save_total_limit=2,
            fp16=torch.cuda.is_available(),
            predict_with_generate=True,
            report_to="none"
        )

    # 5. Trainer Setup
    trainer = Seq2SeqTrainer(
        model=model_bart,
        args=training_args,
        processing_class=tokenizer,
        data_collator=seq2seq_data_collator,
        train_dataset=tokenized_dataset["train"],
        eval_dataset=tokenized_dataset["validation"]
    )

trainer.train()

NameError: name 'trainer' is not defined

In [10]:
from transformers import Seq2SeqTrainer

trainer = Seq2SeqTrainer(
    model=model_bart,
    args=training_args,
    processing_class=tokenizer,
    data_collator=seq2seq_data_collator,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["validation"]
)

print("Trainer created successfully!")

NameError: name 'model_bart' is not defined

In [11]:
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"

print("GPU available:", torch.cuda.is_available())
print("Device:", device)

GPU available: True
Device: cuda

In [12]:
import torch
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

# Check that the GPU is available
if not torch.cuda.is_available():
    raise RuntimeError(
        "GPU is not available. Enable the T4 GPU in Colab first."
    )

device = torch.device("cuda")
model_ckpt = "facebook/bart-large-cnn"

# Load the tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_ckpt)

# Load the BART model onto the GPU
model_bart = AutoModelForSeq2SeqLM.from_pretrained(
    model_ckpt
).to(device)

print("Device:", device)
print("Tokenizer loaded:", tokenizer is not None)
print("BART model loaded:", model_bart is not None)

config.json:   0%|          | 0.00/1.58k [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.63GB

model.safetensors: downloading bytes:           |  0.00B

[transformers] Please make sure the generation config includes `forced_bos_token_id=0`.

Loading weights:   0%|          | 0/511 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

Device: cuda
Tokenizer loaded: True
BART model loaded: True

In [13]:
from datasets import load_dataset, DatasetDict

# Load the legal summarization dataset
dataset_billsum = load_dataset("billsum")

# Split the training data: 90% for training, 10% for validation
train_validation = dataset_billsum["train"].train_test_split(
    test_size=0.1,
    seed=42
)

# Keep the original test sets separate
dataset_billsum = DatasetDict({
    "train": train_validation["train"],
    "validation": train_validation["test"],
    "test": dataset_billsum["test"],
    "ca_test": dataset_billsum["ca_test"]
})

# Check the splits
for split in dataset_billsum:
    print(f"{split}: {len(dataset_billsum[split])} examples")

print("Columns:", dataset_billsum["train"].column_names)

README.md:   0%|          | 0.00/7.27k [00:00<?, ?B/s]

HfUriError: Invalid HF URI 'hf://datasets/billsum@3d8510441c06a3d9dfb32eb0d7f80151730bcc4f/.huggingface.yaml'. Repository id must be 'namespace/name', got 'billsum'.

In [14]:
from datasets import load_dataset, DatasetDict

# Load BillSum using its full Hugging Face repository ID
raw_billsum = load_dataset("FiscalNote/billsum")

# Create a validation split from the training data
train_validation = raw_billsum["train"].train_test_split(
    test_size=0.1,
    seed=42
)

# Keep the original test sets separate
dataset_billsum = DatasetDict({
    "train": train_validation["train"],
    "validation": train_validation["test"],
    "test": raw_billsum["test"],
    "ca_test": raw_billsum["ca_test"]
})

# Verify the dataset
for split in dataset_billsum:
    print(f"{split}: {len(dataset_billsum[split])} examples")

print("Columns:", dataset_billsum["train"].column_names)

README.md:   0%|          | 0.00/7.27k [00:00<?, ?B/s]

data/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 91.8MB

data/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

data/test-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 15.8MB

data/test-00000-of-00001.parquet: downloading bytes:           |  0.00B

data/ca_test-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 6.12MB

data/ca_test-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/18949 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/3269 [00:00<?, ? examples/s]

Generating ca_test split:   0%|          | 0/1237 [00:00<?, ? examples/s]

train: 17054 examples
validation: 1895 examples
test: 3269 examples
ca_test: 1237 examples
Columns: ['text', 'summary', 'title']

In [15]:
def convert_examples_to_features(example_batch):
    # Tokenize the legal documents
    input_encodings = tokenizer(
        example_batch["text"],
        max_length=1024,
        truncation=True
    )

    # Tokenize the reference summaries
    target_encodings = tokenizer(
        text_target=example_batch["summary"],
        max_length=128,
        truncation=True
    )

    return {
        "input_ids": input_encodings["input_ids"],
        "attention_mask": input_encodings["attention_mask"],
        "labels": target_encodings["input_ids"]
    }

In [16]:
tokenized_dataset = dataset_billsum.map(
    convert_examples_to_features,
    batched=True,
    remove_columns=dataset_billsum["train"].column_names
)

print(tokenized_dataset)

Map:   0%|          | 0/17054 [00:00<?, ? examples/s]

Map:   0%|          | 0/1895 [00:00<?, ? examples/s]

Map:   0%|          | 0/3269 [00:00<?, ? examples/s]

Map:   0%|          | 0/1237 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 17054
    })
    validation: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 1895
    })
    test: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 3269
    })
    ca_test: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 1237
    })
})

In [17]:
tokenized_dataset = dataset_billsum.map(
    convert_examples_to_features,
    batched=True,
    remove_columns=dataset_billsum["train"].column_names
)

print(tokenized_dataset)

DatasetDict({
    train: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 17054
    })
    validation: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 1895
    })
    test: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 3269
    })
    ca_test: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 1237
    })
})

In [18]:
print("Available splits:", list(tokenized_dataset.keys()))

for split in tokenized_dataset:
    print(f"{split}: {len(tokenized_dataset[split])} examples")

print("Features:", tokenized_dataset["train"].column_names)

Available splits: ['train', 'validation', 'test', 'ca_test']
train: 17054 examples
validation: 1895 examples
test: 3269 examples
ca_test: 1237 examples
Features: ['input_ids', 'attention_mask', 'labels']

In [19]:
from transformers import DataCollatorForSeq2Seq

seq2seq_data_collator = DataCollatorForSeq2Seq(
    tokenizer=tokenizer,
    model=model_bart
)

print("Data collator created successfully!")

Data collator created successfully!

In [20]:
import os
import torch
from transformers import Seq2SeqTrainingArguments

output_dir = "/content/drive/MyDrive/Text-Summarizer/bart-billsum"

os.makedirs(output_dir, exist_ok=True)

training_args = Seq2SeqTrainingArguments(
    output_dir=output_dir,
    num_train_epochs=1,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=4,
    warmup_steps=500,
    weight_decay=0.01,
    logging_steps=100,
    eval_strategy="steps",
    eval_steps=500,
    save_strategy="steps",
    save_steps=500,
    save_total_limit=2,
    fp16=torch.cuda.is_available(),
    predict_with_generate=True,
    report_to="none"
)

print("Training arguments configured successfully!")

Training arguments configured successfully!

In [21]:
from transformers import Seq2SeqTrainer

trainer = Seq2SeqTrainer(
    model=model_bart,
    args=training_args,
    processing_class=tokenizer,
    data_collator=seq2seq_data_collator,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["validation"]
)

print("Trainer created successfully!")

Trainer created successfully!

In [22]:
/content/drive/MyDrive/Text-Summarizer/bart-billsum

NameError: name 'content' is not defined

In [23]:
train_result = trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

In [24]:
import os

final_model_dir = (
    "/content/drive/MyDrive/Text-Summarizer/bart-billsum/final"
)

os.makedirs(final_model_dir, exist_ok=True)

trainer.save_model(final_model_dir)
tokenizer.save_pretrained(final_model_dir)

print("Final BART model and tokenizer saved successfully!")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Final BART model and tokenizer saved successfully!

In [25]:
import os

final_model_dir = (
    "/content/drive/MyDrive/Text-Summarizer/bart-billsum/final"
)

os.makedirs(final_model_dir, exist_ok=True)

trainer.save_model(final_model_dir)
tokenizer.save_pretrained(final_model_dir)

print("Model and tokenizer saved successfully!")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model and tokenizer saved successfully!

In [26]:
import os

print(os.listdir(final_model_dir))

['config.json', 'generation_config.json', 'model.safetensors', 'tokenizer_config.json', 'tokenizer.json', 'training_args.bin']

In [27]:
!pip install -q evaluate rouge_score

  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 4.1 MB/s eta 0:00:00
  Building wheel for rouge_score (setup.py) ... done

In [28]:
import evaluate

rouge = evaluate.load("rouge")

print("ROUGE loaded successfully!")

Downloading builder script: 0.00B [00:00, ?B/s]

ROUGE loaded successfully!

In [29]:
import torch
from tqdm.auto import tqdm

def calculate_rouge(
    dataset,
    model,
    tokenizer,
    metric,
    batch_size=1
):
    model.eval()

    predictions = []
    references = []
    device = next(model.parameters()).device

    for start in tqdm(range(0, len(dataset), batch_size)):
        batch = dataset[start:start + batch_size]

        inputs = tokenizer(
            batch["text"],
            max_length=1024,
            truncation=True,
            padding=True,
            return_tensors="pt"
        )

        inputs = {
            key: value.to(device)
            for key, value in inputs.items()
        }

        with torch.inference_mode():
            generated_tokens = model.generate(
                **inputs,
                max_new_tokens=128,
                num_beams=2,
                do_sample=False
            )

        decoded_predictions = tokenizer.batch_decode(
            generated_tokens,
            skip_special_tokens=True
        )

        predictions.extend(decoded_predictions)
        references.extend(batch["summary"])

    scores = metric.compute(
        predictions=predictions,
        references=references,
        use_stemmer=True
    )

    return scores

In [30]:
test_sample = dataset_billsum["test"].select(range(100))

rouge_scores = calculate_rouge(
    dataset=test_sample,
    model=model_bart,
    tokenizer=tokenizer,
    metric=rouge,
    batch_size=1
)

print("\nROUGE Scores:")
for metric_name, score in rouge_scores.items():
    print(f"{metric_name}: {score:.4f}")

  0%|          | 0/100 [00:00<?, ?it/s]

[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

ROUGE Scores:
rouge1: 0.4935
rouge2: 0.3109
rougeL: 0.3813
rougeLsum: 0.4209

In [31]:
final_rouge_scores = calculate_rouge(
    dataset=dataset_billsum["test"],
    model=model_bart,
    tokenizer=tokenizer,
    metric=rouge,
    batch_size=1
)

print("Final ROUGE scores on the complete test set:")

for metric_name, score in final_rouge_scores.items():
    print(f"{metric_name}: {score:.4f}")

  0%|          | 0/3269 [00:00<?, ?it/s]

[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Final ROUGE scores on the complete test set:
rouge1: 0.4837
rouge2: 0.2996
rougeL: 0.3674
rougeLsum: 0.4042

In [32]:
import json
import os

results_path = (
    "/content/drive/MyDrive/Text-Summarizer/"
    "bart-billsum/rouge_test_scores.json"
)

os.makedirs(os.path.dirname(results_path), exist_ok=True)

with open(results_path, "w") as f:
    json.dump(final_rouge_scores, f, indent=4)

print("ROUGE results saved to Google Drive:", results_path)

ROUGE results saved to Google Drive: /content/drive/MyDrive/Text-Summarizer/bart-billsum/rouge_test_scores.json

In [33]:
import os
import json

# Save evaluation scores in temporary Colab storage
scores = {
    name: float(value)
    for name, value in final_rouge_scores.items()
}

with open("/content/rouge_test_scores.json", "w") as f:
    json.dump(scores, f, indent=4)

# Save the currently loaded, fine-tuned BART model
local_model_dir = "/content/bart-billsum-final"

model_bart.save_pretrained(
    local_model_dir,
    safe_serialization=True
)

tokenizer.save_pretrained(local_model_dir)

print("ROUGE scores saved locally.")
print("Model and tokenizer saved locally.")
print("Model files:", os.listdir(local_model_dir))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

ROUGE scores saved locally.
Model and tokenizer saved locally.
Model files: ['tokenizer_config.json', 'model.safetensors', 'generation_config.json', 'tokenizer.json', 'config.json']

In [34]:
import torch

# Prediction settings
gen_kwargs = {
    "num_beams": 4,
    "length_penalty": 0.8,
    "max_new_tokens": 128,
    "early_stopping": True
}

# Select one legal document from the test set
sample = dataset_billsum["test"][0]

sample_text = sample["text"]
reference = sample["summary"]

# Tokenize the legal document
inputs = tokenizer(
    sample_text,
    max_length=1024,
    truncation=True,
    return_tensors="pt"
)

# Move inputs to the same device as BART
inputs = {
    key: value.to(model_bart.device)
    for key, value in inputs.items()
}

# Generate a summary
model_bart.eval()

with torch.inference_mode():
    generated_tokens = model_bart.generate(
        **inputs,
        **gen_kwargs
    )

prediction = tokenizer.decode(
    generated_tokens[0],
    skip_special_tokens=True
)

# Display the results
print("LEGAL DOCUMENT:")
print(sample_text[:1500])

print("\nREFERENCE SUMMARY:")
print(reference)

print("\nBART GENERATED SUMMARY:")
print(prediction)

[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

LEGAL DOCUMENT:
SECTION 1. ENVIRONMENTAL INFRASTRUCTURE.

    (a) Jackson County, Mississippi.--Section 219 of the Water
Resources Development Act of 1992 (106 Stat. 4835; 110 Stat. 3757) is
amended--
        (1) in subsection (c), by striking paragraph (5) and inserting
    the following:
        ``(5) Jackson county, mississippi.--Provision of an alternative
    water supply and a project for the elimination or control of
    combined sewer overflows for Jackson County, Mississippi.''; and
        (2) in subsection (e)(1), by striking ``$10,000,000'' and
    inserting ``$20,000,000''.
    (b) Manchester, New Hampshire.--Section 219(e)(3) of the Water
Resources Development Act of 1992 (106 Stat. 4835; 110 Stat. 3757) is
amended by striking ``$10,000,000'' and inserting ``$20,000,000''.
    (c) Atlanta, Georgia.--Section 219(f)(1) of the Water Resources
Development Act of 1992 (106 Stat. 4835; 113 Stat. 335) is amended by
striking ``$25,000,000 for''.
    (d) Paterson, Passaic County, and Passaic Valley, New Jersey.--
Section 219(f)(2) of the Water Resources Development Act of 1992 (106
Stat. 4835; 113 Stat. 335) is amended by striking ``$20,000,000 for''.
    (e) Elizabeth and North Hudson, New Jersey.--Section 219(f) of the
Water Resources Development Act of 1992 (106 Stat. 4835; 113 Stat. 335)
is amended--
        (1) in paragraph (33), by striking ``$20,000,000'' and
    inserting ``$10,000,000''; and
        (2) in paragraph (34)--
            (A) by striking ``$10,000,000

REFERENCE SUMMARY:
Amends the Water Resources Development Act of 1999 to: (1) authorize appropriations for FY 1999 through 2009 for implementation of a long-term resource monitoring program with respect to the Upper Mississippi River Environmental Management Program (currently, such funding is designated for a program for the planning, construction, and evaluation of measures for fish and wildlife habitat rehabilitation and enhancement); (2) authorize the Secretary of the Army to carry out modifications to the navigation project for the Delaware River, Pennsylvania and Delaware, if such project as modified is technically sound, environmentally (currently, economically) acceptable, and economically justified; (3) subject certain previously deauthorized water resources development projects to the seven-year limitation governing project deauthorizations under the Act, with the exception of such a project for Indian River County, Florida; (4) except from a certain schedule of the non-Federal cost of the periodic nourishment of shore protection projects constructed after December 31, 1999, those projects for which a District Engineer's Report has been completed by such date;  (5) require that the project cooperation agreement for the Comite River Diversion Project for flood control include a provision that specifies that any reduction in the non-Federal share that results from certain modifications be credited toward the share of project costs to be paid by the Amite River Basin Drainage and Water Conservation District; (6) allow the Secretary to provide additional compensation to Chesapeake City, Maryland (currently, to the City of Chesapeake, Maryland) for damage to its water supply resulting from the Chesapeake and Delaware Canal Project; (7) provide for the submission of certain reports on water resources development projects by the Secretary, notwithstanding Federal reporting termination provisions; and (8) authorize and provide for an authorization of appropriations for the existing program for the safety and operations expenses of the Federal Railroad Administration, and make available for obligation funds currently appropriated for such program.

BART GENERATED SUMMARY:
Amends the Water Resources Development Act of 1992 to: (1) increase from $10 million to $20 million the amount of funds authorized to be provided to Jackson County, Mississippi, for the provision of an alternative water supply and a project for the elimination or control of combined sewer overflows for Jackson County; (2) increase the amount authorized for the Upper Mississippi River Environmental Management Program; (3) authorize appropriations for the Delaware River, Pennsylvania, and Delaware River projects; (4) reauthorize through FY 2000 the project reauthorization program; (5) authorize the Secretary of the Interior to carry out projects

In [35]:
import torch

def summarize_legal_document(
    legal_text,
    max_input_length=1024,
    max_new_tokens=128
):
    if not isinstance(legal_text, str) or not legal_text.strip():
        raise ValueError("Please provide a non-empty legal document.")

    model_bart.eval()
    device = next(model_bart.parameters()).device

    inputs = tokenizer(
        legal_text,
        max_length=max_input_length,
        truncation=True,
        return_tensors="pt"
    )

    inputs = {
        key: value.to(device)
        for key, value in inputs.items()
    }

    with torch.inference_mode():
        summary_ids = model_bart.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            num_beams=4,
            length_penalty=0.8,
            early_stopping=True,
            no_repeat_ngram_size=3
        )

    summary = tokenizer.decode(
        summary_ids[0],
        skip_special_tokens=True
    )

    return summary


print("Legal summarization function created successfully!")

Legal summarization function created successfully!

In [36]:
sample_legal_text = dataset_billsum["test"][1]["text"]

generated_summary = summarize_legal_document(
    sample_legal_text
)

print("GENERATED LEGAL SUMMARY:")
print(generated_summary)

[transformers] Both `max_new_tokens` (=128) and `max_length`(=142) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

GENERATED LEGAL SUMMARY:
Federal Forage Fee Act of 1993 - Requires all grazing operations conducted on Federal lands to be subject to all applicable Federal, State, and local laws, including but not limited to:  (1) the Animal Damage Control Act; (2) the Bankhead-Jones Farm Tenant Act; and (3) the Clean Air Act, the Endangered Species Act of 1973, the Federal Advisory Committee Act, Federal Grant and Cooperative Agreement Act of 1977, Federal Insecticide, Fungicide, and Rodenticide Act, and Federal Land Policy and Management Act of 1976.
Directs the Secretary of the Interior to